// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__XoeoihGo88QhKHfuwnB8sZeN6y7dUc',
    appId: '1:370150444522:web:612def483b826bfa52f693',
    messagingSenderId: '370150444522',
    projectId: 'fruit-hub-86e8a',
    authDomain: 'fruit-hub-86e8a.firebaseapp.com',
    storageBucket: 'fruit-hub-86e8a.firebasestorage.app',
    measurementId: 'G-M25ZFQY1FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7kVo90_agh1SWlwYsWXZ3WXRag6wsqmU',
    appId: '1:370150444522:android:0f6d60a1e951bece52f693',
    messagingSenderId: '370150444522',
    projectId: 'fruit-hub-86e8a',
    storageBucket: 'fruit-hub-86e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXq_4_qm0mYbA-3CDEWzMRlBXZcb8AjTA',
    appId: '1:370150444522:ios:4b83c93bbbac547b52f693',
    messagingSenderId: '370150444522',
    projectId: 'fruit-hub-86e8a',
    storageBucket: 'fruit-hub-86e8a.firebasestorage.app',
    androidClientId: '370150444522-2at71ofsf3f5luf9muqaebiebm1rtt02.apps.googleusercontent.com',
    iosClientId: '370150444522-f66llpat58n9e579vb32ku329kk601vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXq_4_qm0mYbA-3CDEWzMRlBXZcb8AjTA',
    appId: '1:370150444522:ios:4b83c93bbbac547b52f693',
    messagingSenderId: '370150444522',
    projectId: 'fruit-hub-86e8a',
    storageBucket: 'fruit-hub-86e8a.firebasestorage.app',
    androidClientId: '370150444522-2at71ofsf3f5luf9muqaebiebm1rtt02.apps.googleusercontent.com',
    iosClientId: '370150444522-f66llpat58n9e579vb32ku329kk601vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA__XoeoihGo88QhKHfuwnB8sZeN6y7dUc',
    appId: '1:370150444522:web:8be4882d214733a452f693',
    messagingSenderId: '370150444522',
    projectId: 'fruit-hub-86e8a',
    authDomain: 'fruit-hub-86e8a.firebaseapp.com',
    storageBucket: 'fruit-hub-86e8a.firebasestorage.app',
    measurementId: 'G-S5GQLJPRF7',
  );
}
